package bpf

//#include "consts.h"
import "C"

const (
	VETH_ID = C.VETH_ID
	FLOW_S  = 12
	STATE_S = 20

	F_STICKY            = C.F_STICKY
	F_NO_SHARE_FLOWS    = C.F_NO_SHARE_FLOWS
	F_NO_TRACK_FLOWS    = C.F_NO_TRACK_FLOWS
	F_NO_ESTIMATE_CONNS = C.F_NO_ESTIMATE_CONNS
	F_NO_STORE_STATS    = C.F_NO_STORE_STATS
)
